//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SosyalKaldık.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETKINLIK
    {
        public int ETK_ID { get; set; }
        public string ETK_BASLIK { get; set; }
        public string ETK_ACIKLAMA { get; set; }
        public string ETK_SEHIR { get; set; }
        public string ETK_ILCE { get; set; }
        public System.DateTime ETK_TARIH_SAAT { get; set; }
        public int KUL_ID { get; set; }
        public int KAT_ID { get; set; }
    
        public virtual KATEGORI KATEGORI { get; set; }
        public virtual KULLANICI KULLANICI { get; set; }
    }
}
