//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SosyalKaldık.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kategoriler
    {
        public string ETK_BASLIK { get; set; }
        public string ETK_ACIKLAMA { get; set; }
        public string ETK_SEHIR { get; set; }
        public System.DateTime ETK_TARIH_SAAT { get; set; }
        public string ETK_ILCE { get; set; }
        public string KAT_ADI { get; set; }
        public string KUL_EMAIL { get; set; }
        public string KUL_TELEFON { get; set; }
        public string KUL_ADI { get; set; }
        public string KUL_SOYADI { get; set; }
    }
}
