//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SosyalKaldık.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANICI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KULLANICI()
        {
            this.ETKINLIKs = new HashSet<ETKINLIK>();
        }
    
        public int KUL_ID { get; set; }
        public string KUL_EMAIL { get; set; }
        public string KUL_PASSWORD { get; set; }
        public string KUL_TELEFON { get; set; }
        public string KUL_ADI { get; set; }
        public string KUL_SOYADI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ETKINLIK> ETKINLIKs { get; set; }
    }
}
